version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "00:00"
    assignees:
      - "MaxxusX"
    commit-message:
      prefix: "[actions] "

  - package-ecosystem: "npm"
    directory: "/"
    versioning-strategy: "increase"
    groups:
      non-major:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
      sec-non-major:
        applies-to: "security-updates"
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "00:00"
    assignees:
      - "MaxxusX"
    commit-message:
      prefix: "[pnpm] "

